src/Entity/RequestLog.php
<?php

    namespace App\Entity;

    use Doctrine\ORM\Mapping as ORM;

    /**
     * @ORM\Entity(repositoryClass="App\Repository\RequestLogRepository")
     * @ORM\Table(name="request_log")
     * @ORM\HasLifecycleCallbacks()
     */
    class RequestLog
    {

        use Traits\Id;
        use Traits\Shop;
        use Traits\Dates;

        /**
         * @var string
         * @ORM\Column(type="string")
         */
        protected $url;

        /**
         * @var string
         * @ORM\Column(type="string")
         */
        protected $method;

        /**
         * @var array
         * @ORM\Column(type="array")
         */
        protected $request = [];

        /**
         * @var array
         * @ORM\Column(type="array")
         */
        protected $response = [];

        /**
         * @return string
         */
        public function getUrl() : string
        {
            return $this->url;
        }

        /**
         * @param string $url
         * @return self
         */
        public function setUrl(string $url) : self
        {
            $this->url = $url;
            return $this;
        }

        /**
         * @return string
         */
        public function getMethod() : string
        {
            return $this->method;
        }

        /**
         * @param string $method
         * @return self
         */
        public function setMethod(string $method) : self
        {
            $this->method = $method;
            return $this;
        }

        /**
         * @return array
         */
        public function getRequest() : array
        {
            return $this->request;
        }

        /**
         * @param array $request
         * @return self
         */
        public function setRequest(array $request) : self
        {
            $this->request = $request;
            return $this;
        }

        /**
         * @return array
         */
        public function getResponse() : array
        {
            return $this->response;
        }

        /**
         * @param array $response
         * @return self
         */
        public function setResponse(array $response) : self
        {
            $this->response = $response;
            return $this;
        }

        /**
         * @return false|string
         */
        public function getResponsePrint()
        {
            return \json_encode($this->getResponse(), \JSON_PRETTY_PRINT | \JSON_UNESCAPED_SLASHES | \JSON_UNESCAPED_UNICODE);
        }

        /**
         * @return false|string
         */
        public function getRequestPrint()
        {
            return \json_encode($this->getRequest(), \JSON_PRETTY_PRINT | \JSON_UNESCAPED_SLASHES | \JSON_UNESCAPED_UNICODE);
        }
    }

templates/app/configuration.html.twig
{% extends 'base.html.twig' %}
{% block body %}
	<div class="container">

		{{ form_start(form) }}

		<div class="form-group row">
			{{ form_label(form.apiKey, null, {label_attr : {'class' : 'col-sm-3 col-form-label'}}) }}
			<div class="col-sm-6">
				{{ form_widget(form.apiKey, {attr : {'class' : 'form-control'}}) }}
			</div>
		</div>

		<div class="form-group row">
			{{ form_label(form.apiKeyTest, null, {label_attr : {'class' : 'col-sm-3 col-form-label'}}) }}
			<div class="col-sm-6">
				{{ form_widget(form.apiKeyTest, {attr : {'class' : 'form-control'}}) }}
			</div>
		</div>

		<div class="form-group row">
			{{ form_label(form.canceledStatus, null, {label_attr : {'class' : 'col-sm-3 col-form-label'}}) }}
			<div class="col-sm-6">
				{{ form_widget(form.canceledStatus, {attr : {'class' : 'form-control'}}) }}
			</div>
		</div>

		<div class="form-group row">
			<div class="col-sm-6 offset-sm-3">
				<div class="form-check ">
					{{ form_widget(form.testMode, {attr : {'class' : 'form-check-input'}}) }}
					{{ form_label(form.testMode, null, {label_attr : {'class' : 'form-check-label'}}) }}
				</div>
			</div>
		</div>

		<div class="form-group row">
			<div class="col-sm-6 offset-sm-3">
				<div class="form-check ">
					{{ form_widget(form.devEnv, {attr : {'class' : 'form-check-input'}}) }}
					{{ form_label(form.devEnv, null, {label_attr : {'class' : 'form-check-label'}}) }}
				</div>
			</div>
		</div>

		<div class="form-group row">
			<div class="col-sm-6 offset-sm-3">
				<div class="form-check ">
					{{ form_widget(form.updateStatuses, {attr : {'class' : 'form-check-input'}}) }}
					{{ form_label(form.updateStatuses, null, {label_attr : {'class' : 'form-check-label'}}) }}
				</div>
			</div>
		</div>

		<div class="form-group row">
			<div class="col-sm-6 offset-sm-3">
				<div class="form-check ">
					{{ form_widget(form.useCustomStatuses, {attr : {'class' : 'form-check-input'}}) }}
					{{ form_label(form.useCustomStatuses, null, {label_attr : {'class' : 'form-check-label'}}) }}
				</div>
			</div>
		</div>

		<div class="form-group row">
			<div class="col-sm-6 offset-sm-3">
				<input type="submit" value="{% trans %}app.configure.button.save{% endtrans %}" class="btn btn-success">
			</div>
		</div>

		{{ form_end(form) }}
	</div>
{% endblock %}

templates/app/logs.html.twig
{% extends 'base.html.twig' %}
{% block body %}

	<div class="container">
		<div class="float-right">{{ knp_pagination_render(logs) }}</div>
	</div>

	<div class="col-12">
		<table class="table js-result">
			<thead>
				<tr>
					<th>{% trans %}app.logs.table.date{% endtrans %}</th>
					<th>{% trans %}app.logs.table.url{% endtrans %}</th>
					<th>{% trans %}app.logs.table.request{% endtrans %}</th>
					<th>{% trans %}app.logs.table.response{% endtrans %}</th>
				</tr>
			</thead>
			<tbody>
				{% for log in logs %}
					<tr>
						<td>
							<div class="alert alert-success">{{ log.method }}</div>
							{{ log.createAt.format('d.m.Y H:i:s') }}
						</td>
						<td>
							{{ log.url|replace({'ru//' : 'ru<br>/'})|raw }}
						</td>
						<td>
							<pre><code data-language="json">{{ log.requestPrint }}</code></pre>
						</td>
						<td class="response">
							<pre><code data-language="json">{{ log.responsePrint }}</code></pre>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	<div class="container">
		<div class="float-right">{{ knp_pagination_render(logs) }}</div>
	</div>
{% endblock %}
{% block javascripts %}

	{{ parent() }}

	<script type="text/javascript" src="{{ asset('js/rainbow-custom.min.js') }}" ></script>
{% endblock %}
{% block stylesheets %}

	{{ parent() }}
	<link rel="stylesheet" type="text/css" href="{{ asset('css/rainbow.css') }}" />
{% endblock %}

templates/app/menu.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			{% for item in items %}
				<li class="nav-item{% if item.active %} active{% endif %}">
					<a class="nav-link" href="{{ item.url }}">{{ item.title }}</a>
				</li>
			{% endfor %}
		</ul>
		<span class="navbar-text">
			<a href="http://{{ shop.shop }}" class="nav-back-to-shop">{% trans %}app.shop.returnToShop{% endtrans %}</a>
		</span>
	</div>
</nav>

templates/app/order-widget-error.html.twig
{% extends 'base.html.twig' %}
{% block header %}{% endblock %}
{% block body %}{% endblock %}

templates/app/order-widget-other.html.twig
{% extends 'base.html.twig' %}
{% block header %}{% endblock %}
{% block body %}
	<div class="container">

		<p></p>

		<h4>{% trans %}widget.order.title{% endtrans %} {{ order.orderNumber }}</h4>

		<p></p>

		<div class="alert alert-info">
			{% trans %}widget.order.error.payment{% endtrans %}
		</div>
	</div>
{% endblock %}

templates/app/order-widget.html.twig
{% extends 'base.html.twig' %}
{% block header %}{% endblock %}
{% block body %}
	<div class="container">

		<p></p>

		<form action="" method="post">
			<input type="hidden" name="token" value="{{ csrf_token('csrf_token') }}">


			<h4>{% trans %}widget.order.title{% endtrans %} {{ order.orderNumber }}</h4>

			{% if errors|length > 0 %}
				{% for error in errors %}
					<div class="alert-danger alert">
						{{ error }}
					</div>
				{% endfor %}
			{% endif %}

			{% if deal is instanceof('\\App\\Entity\\Deal')  %}

				{% if status is instanceof('\\App\\Entity\\NalozhkaStatus')  %}
					<div class="form-group row">
						<label class="col-12 col-form-label">
							{% trans %}widget.order.deal.status{% endtrans %}:
							{{ status.title }}
						</label>
					</div>
				{% endif %}

				{% if trackings|length > 0 %}
					<h4>{% trans %}widget.order.label.tracking{% endtrans %}</h4>

					{% for tracking in trackings %}
						{% if deliveryProviders[tracking.provider].title is defined %}
							<div class="form-group row">
								<div class="col-3 col-form-label">
									{{ deliveryProviders[tracking.provider].title }}
								</div>
								<div class="col-4 col-form-label">
									{{ tracking.trackNumber }}
								</div>
								<div class="col-3 col-form-label">
									<div class="float-right">
										<a class="btn btn-danger" href="?token={{ csrf_token('remove') }}&action=removeTrack&id={{ tracking.id }}">{% trans %}widget.order.track.remove{% endtrans %}</a>
									</div>
								</div>
							</div>
						{% endif %}
					{% endfor %}
				{% else %}

					<h4>{% trans %}widget.order.label.add-tracking{% endtrans %}</h4>

					<div class="form-group row">
						<label class="col-3 col-form-label">
							{% trans %}widget.order.track.title{% endtrans %}
						</label>
						<div class="col-6">
							<select name="provider" class="form-control">
								{% for provider in deliveryProviders %}
									<option value="{{ provider.provider }}">{{ provider.title }}</option>
								{% endfor %}
							</select>
						</div>
					</div>

					<div class="form-group row">
						<label class="col-3 col-form-label">
							{% trans %}widget.order.track.field{% endtrans %}
						</label>
						<div class="col-6">
							<input type="text" required="required" class="form-control" name="trackNumber" value="">
						</div>
					</div>


					<div class="form-group row">
						<div class="col-6 offset-3">
							<input type="submit" value="{% trans %}widget.order.track.add{% endtrans %}" class="btn-success btn" />
						</div>
					</div>
				{% endif %}
			{% else %}
				<p></p>
				<div class="alert-info alert">
					{% trans %}widget.order.deal.no-start{% endtrans %}
				</div>
			{% endif %}
		</form>
	</div>
{% endblock %}

templates/app/statuses.html.twig
{% extends 'base.html.twig' %}
{% block body %}

	<div class="container">
		<form method="post">


			<div class="form-group row">
				<label class="col-sm-3 col-form-label">{% trans %}app.configure.statuses.nalozhka.title{% endtrans %}</label>
				<label class="col-sm-6 col-form-label">{% trans %}app.configure.statuses.insales.title{% endtrans %}</label>
			</div>

			{% for nalozhkaStatus in statuses %}
				<div class="form-group row">
					<label class="col-sm-3 col-form-label">{{ nalozhkaStatus.title }}</label>
					<div class="col-sm-6">
						<select name="statuses[{{ nalozhkaStatus.id }}]" class="form-control">
							<option value="">Не использовать</option>
							{% for insalesStatus in nalozhkaStatus.statuses %}
								<option{% if insalesStatus.selected %} selected="selected"{% endif %} value="{{ insalesStatus.permalink }}">{{ insalesStatus.title }}</option>
							{% endfor %}
						</select>
					</div>
				</div>
			{% endfor %}

			<div class="form-group row">
				<div class="col-sm-6 offset-sm-3">
					<input type="submit" value="{% trans %}app.configure.button.save{% endtrans %}" class="btn btn-success">
				</div>
			</div>
		</form>
	</div>
{% endblock %}